version: 1
id: the-winton-stock-market-challenge
score:  1769.89707
teams: 829
rank: 8
date: 2022-08-07
organization: Hanyang University
team:
  name: ceo.openj@gmail.com
  members:
    - id: ceo.openj@gmail.com
      name: 김현주(openj012) 