version: 1
id: tabular-playground-series-sep-2021
score:  0.79972
teams: 1942
rank: 1147
date: 2022-08-20
organization: Hanyang University
team:
  name: ceo.openj@gmail.com
  members:
    - id: ceo.openj@gmail.com
      name: 김현주(openj012) 