version: 1
id: cat-in-the-dat
score:  0.80850
teams: 1338
rank: 7
date: 2022-07-08
organization: Hanyang University
team:
  name: ceo.openj@gmail.com
  members:
    - id: ceo.openj@gmail.com
      name: 김현주(openj012) 